### ISSUE TITLE
新手 有些地方没懂

### ISSUE THREAD

**Issue by 625781186** [hunterliu1003/blog#1]
1.建立索引 这一步有点没懂 .
![image](https://user-images.githubusercontent.com/30521429/58006213-23b5e480-7b1a-11e9-8aa7-2d991ac22f4d.png)

不知道应该填什么 
![image](https://user-images.githubusercontent.com/30521429/58006243-32040080-7b1a-11e9-8915-249a84e2f54c.png)

2.另外想在文章中加入代码编辑器 , 应该怎么做呢, ![image.png](https://i.loli.net/2019/05/20/5ce25fa50dc6813254.png)

目前不知道如何加入代码编辑器
![image.png](https://i.loli.net/2019/05/20/5ce260aa07e5589732.png)

**Comment by hunterliu1003** [comment]
先回答你第一個問題
你可以這樣設置索引
集合 ID 就是 Collection, 而字段路徑就是 field 欄位
<img width="713" alt="螢幕快照 2019-05-20 下午4 19 56" src="https://user-images.githubusercontent.com/15190246/58006792-7512a380-7b1b-11e9-84e7-e67f58b55f56.png">

**Comment by hunterliu1003** [comment]
目前是沒有提供加入代碼編輯器的功能
只有在 admin 頁面可以使用代碼編輯器撰寫 markdown

**Comment by 625781186** [comment]
> 目前是沒有提供加入代碼編輯器的功能
> 只有在 admin 頁面可以使用代碼編輯器撰寫 markdown

没有发现代码编辑器呀

**Comment by hunterliu1003** [comment]
要顯示代碼的話可以用 markdown 語法

\```javascript
\```

\```html
\```

**Comment by hunterliu1003** [comment]
如果你需要有代碼編輯器的範例
你可能需要引入的是 codepen 的範例
storybook 的 iframe.html 範例沒辦法附帶代碼編輯器

**Comment by 625781186** [comment]
> 如果你需要有代碼編輯器的範例
> 你可能需要引入的是 codepen 的範例
> storybook 的 iframe.html 範例沒辦法附帶代碼編輯器

好的, 谢谢 .

**Comment by hunterliu1003** [comment]
@625781186 
補充給你 `Markdown-it Custom Style Demo` 的寫法
https://github.com/hunterliu1003/blog/blob/master/articleExample.md

**Comment by 625781186** [comment]
> @625781186
> 補充給你 `Markdown-it Custom Style Demo` 的寫法
> https://github.com/hunterliu1003/blog/blob/master/articleExample.md

![image](https://user-images.githubusercontent.com/30521429/58012735-bdd05980-7b27-11e9-891e-f35654c935d1.png)
成功了 , 谢谢~
